server:
  port: 8090
spring:
  data:
    mongodb:
      username: jcgarciamed
      password: jcgarciamed
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin